### ISSUE TITLE
GraphQL call don't catch error

### ISSUE THREAD

**Issue by flochaz** [aws-samples/amazon-location-service-pettracker-demo#15]
At https://github.com/aws-samples/amazon-location-service-pettracker-demo/blob/3e44e47a137380fc79cbc5ee49915b05efbb9bad/infra/lib/fns/appsync-update-position/src/index.ts#L87 , the try catch don't really catch failed mutation since graphql always send back 200 if the call to the graphql endpoint is successful (whatever is the state of the query or mutation behind).

If something goes wrong here is an example of the `result.body` value with a 200 status code:

```json
{
    "data": null,
    "errors": [
        {
            "path": null,
            "locations": [
                {
                    "line": 3,
                    "column": 27,
                    "sourceName": null
                }
            ],
            "message": "Validation error of type VariableTypeMismatch: Variable type 'CreateUserInput' doesn't match expected type 'CreateUserInput!' @ 'createUser'"
        }
    ]
}
```

I'll suggest to test the presence of errors key and raise an error then.

**Comment by dreamorosi** [comment]
Thank you Florian, I'll address this in the next few days

**Comment by dreamorosi** [comment]
Finally got around fixing this, I have added error handling like you suggested in the commit linked above.
